---
- name: Disable and stop recording on both cameras
  hosts: localhost
  become: true
  gather_facts: no
  tasks:
 
    - name: Disable and stop camera0 service
      service:
        name: camera0
        state: stopped
        enabled: false
        
    # - name: Disable and stop camera1 service
    #   service:
    #     name: camera1
    #     state: stopped
    #     enabled: false
        
    - name: Disable and stop iis3d service
      service:
        name: iis3d
        state: stopped
        enabled: false

    - name: Disable and stop scd30 service
      service:
        name: scd30
        state: stopped
        enabled: false

    - name: Disable and stop uart service
      service:
        name: uart
        state: stopped
        enabled: false

    - name: Disable and stop temp service
      service:
        name: temp
        state: stopped
        enabled: false
