---
- name: Start and enable recording on both cameras
  hosts: localhost
  become: true
  gather_facts: no
  tasks:
 
    - name: Enable and start camera0 service
      service:
        name: camera0
        state: started
        enabled: yes
        
    # - name: Enable and start camera1 service
    #   service:
    #     name: camera1
    #     state: started
    #     enabled: yes

    - name: Enable and start iis3d service
      service:
        name: iis3d
        state: started
        enabled: yes

    - name: Enable and start scd30 service
      service:
        name: scd30
        state: started
        enabled: yes

    - name: Enable and start uart service
      service:
        name: uart
        state: started
        enabled: yes

    - name: Enable and start temp service
      service:
        name: temp
        state: started
        enabled: yes
